spring:
  application:
    name: clinic-management
  
  # Default MySQL Database configuration for local development
  datasource:
    url: jdbc:mysql://sunbit-mysql:30306/my_clinic?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=America/Los_Angeles
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: none # Changed from create-drop to none when using Flyway
    open-in-view: false # Explicitly configure to eliminate warning
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  
  # Enable Flyway for schema management
  flyway:
    enabled: true

---
# Common configuration for all profiles
server:
  port: ${PORT:8085}

jwt:
  # SECURITY: In production, ALWAYS set JWT_SECRET environment variable
  # This default is for development only - NEVER use in production!
  secret: ${JWT_SECRET:devSecretKey123456789012345678901234567890}
  expiration: 86400000

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://frolicking-granita-900c53.netlify.app,http://localhost:3000}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
  allowed-headers: "*"

google:
  oauth:
    client-id: ${GOOGLE_CLIENT_ID:#{null}}
    client-secret: ${GOOGLE_CLIENT_SECRET:#{null}}
    redirect-uri: ${GOOGLE_REDIRECT_URI:https://frolicking-granita-900c53.netlify.app/calendar/callback}
    enabled: ${GOOGLE_CALENDAR_ENABLED:false}

logging:
  level:
    com.clinic: INFO
    org.springframework.security: WARN
    org.hibernate: WARN 