spring:
  application:
    name: clinic-management
  
  # Production Database (Railway MySQL)
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:my_clinic}?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=America/Los_Angeles
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA configuration for production
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update  # Safe for production - only updates schema
    show-sql: false  # Disable SQL logging in production
    properties:
      hibernate:
        format_sql: false

# Server configuration
server:
  port: ${PORT:8085}

# JWT configuration
jwt:
  secret: ${JWT_SECRET:${random.value}}
  expiration: 86400000 # 24 hours

# CORS configuration - Allow Netlify domain
cors:
  allowed-origins: ${FRONTEND_URL:https://frolicking-granita-900c53.netlify.app}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"

# Logging
logging:
  level:
    com.clinic: INFO
    org.springframework.security: WARN 