spring:
  application:
    name: clinic-management
  
  # Default MySQL Database configuration for local development
  datasource:
    url: jdbc:mysql://localhost:3306/clinic_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  
  # Flyway is disabled by default for local development
  flyway:
    enabled: false

---
# Production configuration (ACTIVATED IF SPRING_PROFILES_ACTIVE=production)
spring:
  config:
    activate:
      on-profile: production
  
  # Railway MySQL configuration
  datasource:
    url: ${SPRING_DATASOURCE_URL} # Provided by Railway env var
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate # Let Flyway manage the schema

  # Flyway is ENABLED for production
  flyway:
    enabled: true
    baseline-on-migrate: true

---
# Common configuration for all profiles
server:
  port: ${PORT:8085}

jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: 86400000

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://frolicking-granita-900c53.netlify.app,http://localhost:3000}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
  allowed-headers: "*"

google:
  oauth:
    client-id: ${GOOGLE_CLIENT_ID:#{null}}
    client-secret: ${GOOGLE_CLIENT_SECRET:#{null}}
    redirect-uri: ${GOOGLE_REDIRECT_URI:https://frolicking-granita-900c53.netlify.app/calendar/callback}

logging:
  level:
    com.clinic: INFO
    org.springframework.security: WARN
    org.hibernate: WARN 