# Default configuration (Local Development with H2)
spring:
  application:
    name: clinic-management
  
  # Local H2 Database configuration
  datasource:
    url: jdbc:h2:mem:clinic_db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  
  # Local JPA configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop  # Reset H2 on restart
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  
  # H2 Console for local development
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # Flyway disabled - using ddl-auto
  flyway:
    enabled: false

---
# Production configuration (Railway with PostgreSQL)
spring:
  config:
    activate:
      on-profile: production
  
  # Railway PostgreSQL Database configuration
  datasource:
    url: ${DATABASE_URL}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driverClassName: org.postgresql.Driver
  
  # Production JPA configuration - FORCE AGGRESSIVE schema recreation
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate # Use validate with Flyway
    show-sql: true # Enable for debugging on Railway
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  # Flyway enabled - to manage database schema
  flyway:
    enabled: true # Enable Flyway for production
    baseline-on-migrate: true # Creates a baseline if tables already exist

  # Disable H2 console in production
  h2:
    console:
      enabled: false

---
# Common configuration for all profiles
server:
  port: ${PORT:8085}

jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: 86400000

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://frolicking-granita-900c53.netlify.app,http://localhost:3000}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
  allowed-headers: "*"

google:
  oauth:
    client-id: ${GOOGLE_CLIENT_ID:#{null}}
    client-secret: ${GOOGLE_CLIENT_SECRET:#{null}}
    redirect-uri: ${GOOGLE_REDIRECT_URI:https://frolicking-granita-900c53.netlify.app/calendar/callback}

logging:
  level:
    com.clinic: INFO
    org.springframework.security: WARN
    org.hibernate: WARN 