spring:
  application:
    name: clinic-management
  
  # Database configuration - Railway compatible
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:clinic_db}
    driverClassName: ${DATABASE_DRIVER:org.h2.Driver}
    username: ${PGUSER:sa}
    password: ${PGPASSWORD:password}
  
  # JPA configuration - Railway compatible
  jpa:
    database-platform: ${DATABASE_DIALECT:org.hibernate.dialect.H2Dialect}
    hibernate:
      ddl-auto: ${DDL_AUTO:create-drop}  # Railway can override this
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  
  # H2 Console (only for local development)
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:true}
      path: /h2-console
  
  # Flyway configuration
  flyway:
    enabled: ${FLYWAY_ENABLED:false}  # Disabled by default, Railway can enable
    baseline-on-migrate: true
    validate-on-migrate: false
    locations: classpath:db/migration
    
# Server configuration  
server:
  port: ${PORT:8085}

# JWT configuration
jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: 86400000 # 24 hours

# CORS configuration
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://frolicking-granita-900c53.netlify.app,http://localhost:3000}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
  allowed-headers: "*"

# Google OAuth configuration
google:
  oauth:
    client-id: ${GOOGLE_CLIENT_ID:#{null}}
    client-secret: ${GOOGLE_CLIENT_SECRET:#{null}}
    redirect-uri: ${GOOGLE_REDIRECT_URI:https://frolicking-granita-900c53.netlify.app/calendar/callback}

# Logging
logging:
  level:
    com.clinic: ${LOG_LEVEL:INFO}
    org.springframework.security: WARN
    org.hibernate: ${HIBERNATE_LOG_LEVEL:WARN} 