# Railway-specific configuration
# This profile is activated when SPRING_PROFILES_ACTIVE=railway

spring:
  application:
    name: clinic-management
  
  # Railway database configuration
  datasource:
    url: ${DATABASE_URL}
    driverClassName: org.postgresql.Driver
    username: ${PGUSER}
    password: ${PGPASSWORD}
  
  # JPA configuration for Railway
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create  # Force schema creation on Railway
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: UTC
  
  # Flyway configuration for Railway
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false
    locations: classpath:db/migration
    
# Server configuration  
server:
  port: ${PORT:8080}

# JWT configuration
jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: 86400000

# CORS configuration for production
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://frolicking-granita-900c53.netlify.app}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
  allowed-headers: "*"

# Google OAuth configuration
google:
  oauth:
    client-id: ${GOOGLE_CLIENT_ID:#{null}}
    client-secret: ${GOOGLE_CLIENT_SECRET:#{null}}
    redirect-uri: ${GOOGLE_REDIRECT_URI:https://frolicking-granita-900c53.netlify.app/calendar/callback}

# Logging for Railway
logging:
  level:
    com.clinic: INFO
    org.springframework.security: WARN
    org.hibernate: WARN 