spring:
  application:
    name: clinic-management
  
  # Database configuration
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:clinic_db}
    # Auto-detect driver based on DATABASE_URL
    driverClassName: ${spring.datasource.driverClassName:}
    username: ${PGUSER:sa}
    password: ${PGPASSWORD:password}
  
  # JPA configuration
  jpa:
    # Auto-detect dialect based on DATABASE_URL
    database-platform: ${spring.jpa.database-platform:}
    hibernate:
      # FORCE create mode when DATABASE_URL exists (Railway detection)
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: UTC
  
  # H2 Console (local development only)
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # Flyway disabled - using ddl-auto for schema management
  flyway:
    enabled: false

---
# Local development profile (default when no DATABASE_URL)
spring:
  config:
    activate:
      on-profile: "!railway"
  
  datasource:
    driverClassName: org.h2.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop  # Reset H2 on restart
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---
# Railway production profile (auto-activated when DATABASE_URL exists)
spring:
  config:
    activate:
      on-profile: railway
  
  datasource:
    # Railway provides DATABASE_URL automatically
    driverClassName: org.postgresql.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      # CRITICAL: Force complete schema recreation to fix missing columns
      ddl-auto: create
    show-sql: false
  
  h2:
    console:
      enabled: false

---
# Server and application configuration (applies to all profiles)
server:
  port: ${PORT:8085}

jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: 86400000

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://frolicking-granita-900c53.netlify.app,http://localhost:3000}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
  allowed-headers: "*"

google:
  oauth:
    client-id: ${GOOGLE_CLIENT_ID:#{null}}
    client-secret: ${GOOGLE_CLIENT_SECRET:#{null}}
    redirect-uri: ${GOOGLE_REDIRECT_URI:https://frolicking-granita-900c53.netlify.app/calendar/callback}

logging:
  level:
    com.clinic: INFO
    org.springframework.security: WARN
    org.hibernate: WARN 